drobnikj/crawler-google-places

- package.json
The "main" entry for the NPM package seems to be invalid, since there is no "main.js" in the root folder. This can result in the error message
```
Please verify that the package.json has a valid "main" entry
```
The commit in this PR should fix it
> Fix invalid main entry

- src/utils.js
A quotation mark is missing behind the URL. The correct path is
```
CSS selector: form[action*="https://consent.google.com/"] button
XPATH: //form[contains(@action,'https://consent.google.com')]//button
```
Fixes https://github.com/drobnikj/crawler-google-places/issues/133 together with a300f810674f7ad11511e1fa634242bf3169f65b
> Fix cookie button selector

- src/places_crawler.js
- src/utils.js
The consent screen was not detected (wrong URL regex).
After fixing the detection a couple of JS errors occured (concurrency issues).
Fix both issues.
Also sometimes the old consent screen (overlay) appeared again.
So bring back the old code to handle it.
(Note: I didn't test if handling the overlay works, because the overlay didn't occur in my
testing after changing the code, but the selectors seemed to match.)
Rename waitAndHandleConsentFrame() to waitAndHandleConsentScreen(), because mostly the screen occurs on its own page now.
> Fix consent screen handling

- src/extractors.js
Clicking the back button on the additional info page and on the review page often had no effect which resulted in errors afterwards.
Fix this by clicking the back button repeatedly if the navigation doesn't take place.
> Fix back navigation to details page

- src/extractors.js
The back button was not found sometimes.
Reason (most probably):
In some cases Puppeteer clicked on the position where the button had been shortly before the click.
This way the burger menu item was clicked.
Solution: Directly click the DOM node of the button.
Additional benefit of the solution: If the element isn't present in the page anymore,
no error will occur (puppeteer won't complain about a removed element).
> Fix problem that back button is not found

- package.json
- patches/apify+0.22.5.patch
- src/main.js
- src/places_crawler.js
- src/typedefs.js
- src/utils.js
The Consent page was displayed everytime after opening the browser.
Reasons:
- the CrawlerOption persistCookiesPerSession wasn't set
- After setting it, still no code was executed to put it into the
session
- The SDK_SESSION_POOL_STATE.json was corrupted, because an event
listener to persist the state was added twice which lead to writing it
twice at the same time. This last point was only relevant after
stopping and restarting the crawler.
Fix all of those issues.
Notes: 
- Unfortunately I had to create a patch for Apify to fix the last point. I will also create a PR in that repo soon, so that we can hopefully remove the patch after the next Apify release.
- The expires date is sometimes written wrong into the SDK_SESSION_POOL_STATE.json which seems to be another Apify Bug, but the …
> Remember Consent Cookie

- src/extractors.js
The current selector for detecting the additional info page doesn't work e.g. for
place_id=ChIJX0TiOH9t2jERc787U2mFbZo .
(URL: 
https://www.google.com/maps/search/?api=1&query=place_id:ChIJX0TiOH9t2jERc787U2mFbZo&query_place_id=ChIJX0TiOH9t2jERc787U2mFbZo )
This leads to a broken JSON output containing:
```
"additionalInfo": {
"": []
},
```
> Fix detection of the additional info page

- src/main.js
Some weeks ago startUrls in INPUT.json could be strings.
Currently all strings have to be wrapped into an object with with field "url".
This PR brings back the support for strings as startUrls.
> Allow strings as startUrls in INPUT.json

- src/detail_page_handle.js
In PR #191 the source for the flag "permanently closed" was changed. It is now extracted from number 203 of the JSON data array (`jsonData?.[203]?.[1]?.[4]?.[0]`). This works well for most cases, for example these two places in Berlin
```
https://www.google.com/maps/place/?q=place_id:ChIJzxaPaexRqEcRLZw2jr74mQ8
https://www.google.com/maps/place/?q=place_id:ChIJe0A0-FVQqEcR7kn-3YZq7dg
```
Unfortunately there are some edge cases where number 203 contains only null values, for instance for the following two places in Vietnam
```
https://www.google.com/maps/place/?q=place_id:ChIJCZhZMkBLODERhhBTKOZusEo
https://www.google.com/maps/place/?q=place_id:ChIJD9PtlUNaODERMnAK5xM9kZ0
```
...which can be fetched by specifying the Google place ID in the "searchStringsArray" parameter...
``` …
```
> Fix edge cases for permanently closed flag

- src/extractors.js
https://github.com/drobnikj/crawler-google-places/issues/196
Google removed .section-hero-header-image-hero-containe class.
To fix this we will use "[jsaction="pane.heroHeaderImage.click"]"
> Fixing Image scraping class

- src/extractors/general.js
The additional infos are not extracted anymore.
Example place_id, where it doesn't work:
ChIJ386XmIGTB0cR3YPBIkkQ2Ic
The extracted data looks like this in the JSON:
```
"additionalInfo": {
"": []
},
```
> Fix additional-info extraction

- src/extractors/general.js
Amenities for hotels are not extracted anymore because the selectors have changed. `hotel-amenity-name` is no longer used as a CSS class. 
In addition to #208
> Fix additional information for hotels

- README.md
- src/detail_page_handle.js
- src/enqueue_places.js
- src/extractors/general.js
This PR modifies the scraper to fetch all categories in addition to the main category `categoryName`.
The `categoryName` which is extracted by the crawler is one of multiple categories stored internally by Google Maps. If we examine the JSON data we can find all categories in block number 13. For example "The PUB Praha 2" in Prague which has the place ID `ChIJXRQlXoyUC0cRq5R4OBRKKxU` is not only classified as a "Restaurant", but also as a "Bar". Another example is the Jaffa restaurant in Prague which has the place ID `ChIJ0xa6j02VC0cRa7hlPXhPtlI`. It has one `categoryName="Lebanese restaurant"` but 9 categories in total ("Lebanese restaurant", "Barbecue restaurant", "Falafel restaurant", "Halal restaurant", "Hookah bar", "Mediterranean restaurant", "Middle Eastern restaurant", "Mutton …
> Extract all categories

- src/extractors/general.js
PR https://github.com/drobnikj/crawler-google-places/pull/214 introduced a bug 🐞   for places which have absolutely no categories, for example for this place in São Paulo which is named "Escola De Futebol":
```
https://www.google.com/maps/place/?q=place_id:ChIJXbCThiHj3JQRBHtcWwdXq8Y
```
In this case `categories` has a `null` value and it produces the error
```
Error: Operation failed. Error detail: Evaluation failed: TypeError: Cannot read property 'length' of null
```
> Fix for places which have no categories at all

- src/input-validation.js
- src/main.js
- src/utils.js
Should handle links to both csv files and google spreadsheets.
Tested with the following configuration:
```json
{
"startUrls": [
{
"requestsFromUrl": "https://docs.google.com/spreadsheets/d/1Y4JqiSBEoNFDcJqiLAzf9Yo5dh0dLFYfnpFA1ymZTu8/edit#gid=0"
}
],
"maxCrawledPlaces": 10,
"language": "en",
"exportPlaceUrls": false,
"includeHistogram": false,
"includeOpeningHours": false,
"includePeopleAlsoSearch": false,
"additionalInfo": false,
"maxImages": 0,
"maxReviews": 0,
"scrapeReviewerName": true,
"scrapeReviewerId": true,
"scrapeReviewerUrl": true,
"scrapeReviewId": true,
"scrapeReviewUrl": true,
"scrapeResponseFromOwnerText": true,
"proxyConfig": {
"useApifyProxy": true
}
}
```
> Handle start urls loading manually instead of using `RequestList`

- src/enqueue_places.js
Hardware click on search button fails only from apify cloud and only for `iw` language, so one of the three: scrolling into view, getting bounding box or controlling mouse pointer fails under unique Puppeteer-OS-Environment combination, no good reason to find out exactly why in more details.
As a solution added fallback to retry with software click (tested and works) and on top of it another fallback to press Enter key in case if both clicks failed (also works).
All other UI interactions work as expected, proof: https://console.apify.com/view/runs/Ww9ip1gXccKPboW3q
Code snipped below for quick reference:
```
try {
await page.click('#searchbox-searchbutton');
} catch (e) {
log.warning(`click#searchbox-searchbutton ${e?.message}`);
try {
const retryClickSearchButton = await …
```
> Fixed search click for language iw and RTL alike

- CHANGELOG.md
- src/detail_page_handle.js
- src/extractors/general.js
Opening hours sometimes didn't get extracted (https://github.com/drobnikj/crawler-google-places/issues/164).
This PR fixes the issue for most cases by extracting the opening hours directly from a JS variable.
According to a comment in the code it only won't work for some kinds of direct URLs, but search and place IDs will work fine.
If the opening hours can't be extracted from the JS variable, they will be tried to be extracted from the DOM as before.
I tested it with the following start URLs:
```
"https://www.google.com/maps/place/?q=place_id:ChIJa8oexDVDOToRq-Zbla5kHEw",
"https://www.google.com/maps/place/?q=place_id:ChIJzUrRNwVpOToRS5IsdZavgtw", 
"https://www.google.com/maps/place/Bihar+852124,+India/",  
"https://www.google.com/maps/place/McDonald's/@41.5907075,1.6160677,17z/data=!4m5! …
```
> Extract opening hours from JS variable

- CHANGELOG.md
- src/detail_page_handle.js
- src/extractors/general.js
In some rare cases the location field was not scraped, e.g. this usually happened when using the following start URLs locally (Indian postcodes):
```
"https://www.google.com/maps/place/Bihar+852124,+India/",
"https://www.google.com/maps/place/Rajasthan+302037%2C+India?hl=en",
"https://www.google.com/maps/place/Gujarat+384003%2C+India?hl=en",
"https://www.google.com/maps/place/Assam+786623%2C+India?hl=en",
"https://www.google.com/maps/place/Rajasthan+303604%2C+India",
"https://www.google.com/maps/place/Kerala+676501%2C+India",
"https://www.google.com/maps/place/Rajasthan+303504%2C+India",
"https://www.google.com/maps/place/Assam+782427%2C+India",
"https://www.google.com/maps/place/Kerala+676501%2C+India",
"https://www.google.com/maps/place/Rajasthan+303504%2C+India"
```
This PR fixes the …
> Extract location field from JSON

- CHANGELOG.md
- src/detail_page_handle.js
- src/extractors/general.js
The _additionalInfo_ field is now extracted directly from the JSON data which makes it much faster if it is present.
For hotels and similar categories and also for some other outlets the usual additional-info section is often not displayed - instead there's often a "Hotel Details" section on the page. Often there's still data for the usual additional-info section in the JSON data which is also extracted and combined with the "Hotel Details" by this PR.
I ran detailed tests for 100 google places - comparing the old with the new result. 
I also checked the log messages for > 1000 google places to make sure that the fallback using the old HTML extraction never extracted data, i.e. it never happened, that no additional data was found in the JSON but afterwards found in the HTML.
> Extract additional info from JSON

- src/consts.js
- src/main.js
- src/utils.js
Fixes #262
This performance optimization gets significant only for large number or search queries. I tested it with ~30K queries that originally took ±1.5 minutes before the first result appeared in the dataset. Limiting the number of synchronous starts requests reduced the time to ± 45 seconds for 10K, 20K or 30K requests.
See the example [INPUT.json](https://gist.github.com/lhotanok/50070e27c01e37bdf49a2d4f9a101548).
> Enqueue start requests over `500` limit asynchronously

- src/detail_page_handle.js
- src/extractors/general.js
The extraction of the _temporarily closed_ flag didn't work anymore.
Example URL: https://www.google.com/maps/place/?q=place_id:ChIJQcAXtd8udTER8aikz7qMoEI
It also updates the backup version for the _permanently closed_ extraction,
although the _permanently closed_ extraction worked fine.
> Fix temporarily closed extraction

- src/extractors/reviews.js
Increases timeout for the `waitForResponse` function, waiting for the reviews. Solves [this issue](https://app.zenhub.com/workspaces/delivery---solutions-603752b8737ef4001c68296c/issues/apify-projects/delivery-issue-tracker/1120).
> Fix reviews

- CHANGELOG.md
- src/place-extractors/general.js
The element for extracting the additional infos from hotels (hotel amenities) has changes.
This PR updates the corresponding CSS selector, although the hotel amenities are usually extracted directly from Javascript which still worked.
> Improve additional info extraction for hotels
