drobnikj/crawler-google-places

- INPUT_SCHEMA.json
- src/enqueue_places_crawler.js
- src/main.js
- src/places_crawler.js
Additional input options requested by customer, maybe not needed or desired in public version?
> Include search terms in output & extend input options to exclude histogram, opening hrs

- README.md
- package.json
- src/main.js
I tested it pretty thoroughly. Added README part. It makes sense only for the US.
> Added proxy country option

- INPUT_SCHEMA.json
- README.md
- src/main.js
- src/places_crawler.js
- src/polygon.js
Fixing issue with null opening hours,
Fixing issue with not escaped locationstring
update readme
> Small bug fixes

- src/main.js
- src/places_crawler.js
- src/polygon.js
Fix maxCrawledPlaces for polygon search
Fix no results for small zoom using polygon search
> small fixes

- src/main.js
- src/polygon.js
Fix inclusion inpolymgon
fix startUrls usage
> polygon and start urls fixes

- README.md
> Update personal data description in README

- src/detail_page_handle.js
- src/utils.js
> Fix small typos

- README.md
Added new API section for SEO and some other small fixes and edits throughout.
> Text changes

- README.md
Closes https://github.com/drobnikj/crawler-google-places/issues/118
> Add documentation for polygon attribute

- CHANGELOG.md
- src/detail_page_handle.js
Add list of possibles delivery retailers, eg. uber,...
> add orderBy attribute

- src/extractors.js
Fix the extraction of opening hours. 
Fixes #146
> Fix extraction of opening hours

- src/extractors.js
The HTML markup for additional information has changed. This PR adjusts the CSS selectors. The proposed fix works for restaurants, bars, cafes and hotels.
Fixes https://github.com/drobnikj/crawler-google-places/issues/147
> Fix selectors for additional info

- src/extractors.js
Google maps changed the HTML for the additional info page.
Update the element selectors accordingly.
> Fix scraping the additional info page

- src/enqueue_places.js
- src/places_crawler.js
Fixed `searchString?.startsWith` and removed image blocking for place pages (otherwise image selector fails)
> Fixed search checkup and image

- src/detail_page_handle.js
Since today the permantlyClosed field is not extracted correctly for the outlet with placeId _ChIJ2ePzR6RGzpQRBouUYXoiIDg_ (and probably many others where this field should be true) anymore.
> Fix permanentlyClosed extraction

- CHANGELOG.md
- src/extractors/general.js
The subTitle extraction doesn't work.
Examples for place_ids with subtitle: ChIJcQNaaBi5pkcRBRzXLvSmf6U, ChIJH_B_wuwQuUcR00B4Al_Kn88
> Fix subTitle extraction

- src/extractors/general.js
Unfortunately my last PR  (#259 ) sometimes lead to extracting subtitles which were not displayed in Google, e.g. for this place id: ChIJ_zP6aacpdTER3w1f2AvB9-c
> Don't extract too many subtitles

- INPUT_SCHEMA.json
- src/enqueue_places.js
- src/input-validation.js
- src/main.js
- src/places_crawler.js
- src/typedefs.js
- src/utils.js
- actor will not fall back to mouse-move results in case if OCR found 0 pins
- Input UI changed to single drop-down below main options, internally `allPlacesNoSearch` still applied for backwards compatibility
I can upgrade SDK as part of this PR, please let me know if I can proceed with upgrade
> OCR upgrade

- src/detail_page_handle.js
@metalwarrior665  parsing upgraded to external widgets from food.ggogle.com since internal page data now randomly available (sometimes we have it as before, sometimes only link to food.ggogle.com)
> newOrderByParsing

- README.md
- src/detail_page_handle.js
Added parsing and updated README, gas prices only available across USA as far as I can see
> Gas prices

- package.json
- src/extractors/reviews.js
- More robust parsing/serializing of the `pb` query parameter
- No duplicate anymore
> Fixing duplicate reviews + better pb parameter handling

- .actor/actor.json
I have updated output schema structure according to latest documentation.
I have added field URL as last column of output table.
> Output schema update
